In [26]:
def f1(x2,x3):
    return (20+(3*x2)-(2*x3))/8

In [27]:
def f2(x1,x3):
    return (32-(4*x1)+(1*x3))/11

In [28]:
def f3(x1,x2):
    return (35-(6*x1)-(3*x2))/12

In [36]:
x1=0
x2=0
x3=0


x1l=[]
x2l=[]
x3l=[]

In [37]:
#gauss jacobi
import math
for i in range(50000):
    count=0
#     print("\n\n")
#     print("i=",i)
       
#     print("x1t",x1t)
#     print("x2t",x2t)
#     print("x3t",x3t)
#     print("x4t",x4t)
#     print("x5t",x5t)
    x1t=f1(x2,x3)
    x2t=f2(x1,x3)
    x3t=f3(x1,x2)
    
    if abs(x1t-x1)<10**-5:
        break

#     print("executed expressions")
    
#     print("x1",x1)
#     print("x2",x2)
#     print("x3",x3)
#     print("x4",x4)
#     print("x5",x5)
#     print("current values")
    x1=x1t
    x2=x2t
    x3=x3t
    
#     print("x1",x1)
#     print("x2",x2)
#     print("x3",x3)
#     print("x4",x4)
#     print("x5",x5)
#     print("temp val assigned")
    
    x1l.append(x1)
    x2l.append(x2)
    x3l.append(x3)

#     print("added to list")

    if abs(x1)==math.inf:
        print("non converging")
        break

In [38]:
import pandas as pd
df2 = pd.DataFrame(list(zip(x1l, x2l, x3l)), 
               columns =['x1', 'x2', 'x3'])

In [39]:
df2

          x1        x2        x3
0   2.500000  2.909091  2.916667
1   2.861742  2.265152  0.939394
2   3.114583  1.953857  0.919508
3   3.002819  1.860107  0.870911
4   2.979812  1.896330  0.950230
5   2.973566  1.911907  0.952678
6   2.978796  1.914401  0.951907
7   2.979924  1.912429  0.948668
8   2.979994  1.911725  0.948597
9   2.979747  1.911693  0.948738
10  2.979700  1.911795  0.948870